config/routes.rb
Rails.application.routes.draw do
  

  resources :sendattaches
  resources :pretaskmemberships
  resources :predepends
  resources :pretasks
  resources :taskdepends
  resources :jobcomments
  resources :jobposts
  resources :profiles
  resources :talkresps
  resources :projtalks
  
  post'/sendAttachments' => 'projects#sendAttachment'
  get '/getFriends' => 'users#getfriends'
  post '/send_sms' => 'twilio#send_sms'
  resources :deadlines
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :taskmemberships
  resources :projectmemberships
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :users
  resources :friendships
  resources :projects
  resources :tasks
  resources :subtasks
  resources :comments    
  get 'page/index'
  root 'rails_admin/main#dashboard'


  resources :users do
    resources :friendships
    resources :projects do
      resources :tasks do
        resources :subtasks do
          resources :comments
        end
      end
    end
  end


end

app/models/taskdepend.rb
class Taskdepend < ActiveRecord::Base
	belongs_to :task 
	belongs_to :taskdependto, :class_name => "Task"
end

app/controllers/taskdepends_controller.rb
class TaskdependsController < ApplicationController
  before_action :set_taskdepend, only: [:show, :edit, :update, :destroy]

  # GET /taskdepends
  # GET /taskdepends.json
  def index
    @taskdepends = Taskdepend.all
  end

  # GET /taskdepends/1
  # GET /taskdepends/1.json
  def show
  end

  # GET /taskdepends/new
  def new
    @taskdepend = Taskdepend.new
  end

  # GET /taskdepends/1/edit
  def edit
  end

  # POST /taskdepends
  # POST /taskdepends.json
  def create
    @taskdepend = Taskdepend.new(taskdepend_params)

    respond_to do |format|
      if @taskdepend.save
        format.html { redirect_to @taskdepend, notice: 'Taskdepend was successfully created.' }
        format.json { render :show, status: :created, location: @taskdepend }
      else
        format.html { render :new }
        format.json { render json: @taskdepend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /taskdepends/1
  # PATCH/PUT /taskdepends/1.json
  def update
    respond_to do |format|
      if @taskdepend.update(taskdepend_params)
        format.html { redirect_to @taskdepend, notice: 'Taskdepend was successfully updated.' }
        format.json { render :show, status: :ok, location: @taskdepend }
      else
        format.html { render :edit }
        format.json { render json: @taskdepend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taskdepends/1
  # DELETE /taskdepends/1.json
  def destroy
    @taskdepend.destroy
    respond_to do |format|
      format.html { redirect_to taskdepends_url, notice: 'Taskdepend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_taskdepend
      @taskdepend = Taskdepend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def taskdepend_params
      params.require(:taskdepend).permit(:task_id, :taskdependto_id)
    end
end

app/helpers/taskdepends_helper.rb
module TaskdependsHelper
end

app/views/taskdepends/_form.html.erb
<%= form_for(@taskdepend) do |f| %>
  <% if @taskdepend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@taskdepend.errors.count, "error") %> prohibited this taskdepend from being saved:</h2>

      <ul>
      <% @taskdepend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task_id %><br>
    <%= f.number_field :task_id %>
  </div>
  <div class="field">
    <%= f.label :taskdependto_id %><br>
    <%= f.number_field :taskdependto_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/taskdepends/edit.html.erb
<h1>Editing Taskdepend</h1>

<%= render 'form' %>

<%= link_to 'Show', @taskdepend %> |
<%= link_to 'Back', taskdepends_path %>

app/views/taskdepends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Taskdepends</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>Taskdependto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @taskdepends.each do |taskdepend| %>
      <tr>
        <td><%= taskdepend.task_id %></td>
        <td><%= taskdepend.taskdependto_id %></td>
        <td><%= link_to 'Show', taskdepend %></td>
        <td><%= link_to 'Edit', edit_taskdepend_path(taskdepend) %></td>
        <td><%= link_to 'Destroy', taskdepend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Taskdepend', new_taskdepend_path %>

app/views/taskdepends/new.html.erb
<h1>New Taskdepend</h1>

<%= render 'form' %>

<%= link_to 'Back', taskdepends_path %>

app/views/taskdepends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @taskdepend.task_id %>
</p>

<p>
  <strong>Taskdependto:</strong>
  <%= @taskdepend.taskdependto_id %>
</p>

<%= link_to 'Edit', edit_taskdepend_path(@taskdepend) %> |
<%= link_to 'Back', taskdepends_path %>