config/routes.rb
Rails.application.routes.draw do
  

  resources :sendattaches
  resources :pretaskmemberships
  resources :predepends
  resources :pretasks
  resources :taskdepends
  resources :jobcomments
  resources :jobposts
  resources :profiles
  resources :talkresps
  resources :projtalks
  
  post'/sendAttachments' => 'projects#sendAttachment'
  get '/getFriends' => 'users#getfriends'
  post '/send_sms' => 'twilio#send_sms'
  resources :deadlines
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :taskmemberships
  resources :projectmemberships
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :users
  resources :friendships
  resources :projects
  resources :tasks
  resources :subtasks
  resources :comments    
  get 'page/index'
  root 'rails_admin/main#dashboard'


  resources :users do
    resources :friendships
    resources :projects do
      resources :tasks do
        resources :subtasks do
          resources :comments
        end
      end
    end
  end


end

app/models/sendattach.rb
class Sendattach < ActiveRecord::Base
	mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.	   	
   mount_base64_uploader :attachment, AttachmentUploader
end

app/controllers/sendattaches_controller.rb
class SendattachesController < ApplicationController
  before_action :set_sendattach, only: [:show, :edit, :update, :destroy]

  # GET /sendattaches
  # GET /sendattaches.json
  def index
    @sendattaches = Sendattach.all
  end

  # GET /sendattaches/1
  # GET /sendattaches/1.json
  def show
  end

  # GET /sendattaches/new
  def new
    @sendattach = Sendattach.new
  end

  # GET /sendattaches/1/edit
  def edit
  end

  # POST /sendattaches
  # POST /sendattaches.json
  def create
    @sendattach = Sendattach.new(sendattach_params)
    if @sendattach.save
      render json: {status: :success, sendattach: @sendattach}
      SendattachMailer.send_attachment(@sendattach).deliver
    else
      render json: {status: :failed, sendattach: @sendattach}
    end

  end

  # PATCH/PUT /sendattaches/1
  # PATCH/PUT /sendattaches/1.json
  def update
    respond_to do |format|
      if @sendattach.update(sendattach_params)
        format.html { redirect_to @sendattach, notice: 'Sendattach was successfully updated.' }
        format.json { render :show, status: :ok, location: @sendattach }
      else
        format.html { render :edit }
        format.json { render json: @sendattach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sendattaches/1
  # DELETE /sendattaches/1.json
  def destroy
    @sendattach.destroy
    respond_to do |format|
      format.html { redirect_to sendattaches_url, notice: 'Sendattach was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sendattach
      @sendattach = Sendattach.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sendattach_params
      params.require(:sendattach).permit(:name, :email, :description, :attachment)
    end
end

app/helpers/sendattaches_helper.rb
module SendattachesHelper
end

app/views/sendattaches/_form.html.erb
<%= form_for(@sendattach) do |f| %>
  <% if @sendattach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sendattach.errors.count, "error") %> prohibited this sendattach from being saved:</h2>

      <ul>
      <% @sendattach.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :attachment %><br>
    <%= f.file_field :attachment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sendattaches/edit.html.erb
<h1>Editing Sendattach</h1>

<%= render 'form' %>

<%= link_to 'Show', @sendattach %> |
<%= link_to 'Back', sendattaches_path %>

app/views/sendattaches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sendattaches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Description</th>
      <th>Attachment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sendattaches.each do |sendattach| %>
      <tr>
        <td><%= sendattach.name %></td>
        <td><%= sendattach.email %></td>
        <td><%= sendattach.description %></td>
        <td><%= sendattach.attachment %></td>
        <td><%= link_to 'Show', sendattach %></td>
        <td><%= link_to 'Edit', edit_sendattach_path(sendattach) %></td>
        <td><%= link_to 'Destroy', sendattach, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sendattach', new_sendattach_path %>

app/views/sendattaches/new.html.erb
<h1>New Sendattach</h1>

<%= render 'form' %>

<%= link_to 'Back', sendattaches_path %>

app/views/sendattaches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sendattach.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @sendattach.email %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sendattach.description %>
</p>

<p>
  <strong>Attachment:</strong>
  <%= @sendattach.attachment %>
</p>

<%= link_to 'Edit', edit_sendattach_path(@sendattach) %> |
<%= link_to 'Back', sendattaches_path %>