config/routes.rb
Rails.application.routes.draw do
  

  resources :sendattaches
  resources :pretaskmemberships
  resources :predepends
  resources :pretasks
  resources :taskdepends
  resources :jobcomments
  resources :jobposts
  resources :profiles
  resources :talkresps
  resources :projtalks
  
  post'/sendAttachments' => 'projects#sendAttachment'
  get '/getFriends' => 'users#getfriends'
  post '/send_sms' => 'twilio#send_sms'
  resources :deadlines
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :taskmemberships
  resources :projectmemberships
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :users
  resources :friendships
  resources :projects
  resources :tasks
  resources :subtasks
  resources :comments    
  get 'page/index'
  root 'rails_admin/main#dashboard'


  resources :users do
    resources :friendships
    resources :projects do
      resources :tasks do
        resources :subtasks do
          resources :comments
        end
      end
    end
  end


end

app/models/jobcomment.rb
class Jobcomment < ActiveRecord::Base
	belongs_to :user
	belongs_to :jobpost
end

app/controllers/jobcomments_controller.rb
class JobcommentsController < ApplicationController
  before_action :set_jobcomment, only: [:show, :edit, :update, :destroy]

  # GET /jobcomments
  # GET /jobcomments.json
  def index
    @jobcomments = Jobcomment.all
  end

  # GET /jobcomments/1
  # GET /jobcomments/1.json
  def show
  end

  # GET /jobcomments/new
  def new
    @jobcomment = Jobcomment.new
  end

  # GET /jobcomments/1/edit
  def edit
  end

  # POST /jobcomments
  # POST /jobcomments.json
  def create
    @jobcomment = Jobcomment.new(jobcomment_params)

    respond_to do |format|
      if @jobcomment.save
        format.html { redirect_to @jobcomment, notice: 'Jobcomment was successfully created.' }
        format.json { render :show, status: :created, location: @jobcomment }
      else
        format.html { render :new }
        format.json { render json: @jobcomment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobcomments/1
  # PATCH/PUT /jobcomments/1.json
  def update
    respond_to do |format|
      if @jobcomment.update(jobcomment_params)
        format.html { redirect_to @jobcomment, notice: 'Jobcomment was successfully updated.' }
        format.json { render :show, status: :ok, location: @jobcomment }
      else
        format.html { render :edit }
        format.json { render json: @jobcomment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobcomments/1
  # DELETE /jobcomments/1.json
  def destroy
    @jobcomment.destroy
    respond_to do |format|
      format.html { redirect_to jobcomments_url, notice: 'Jobcomment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jobcomment
      @jobcomment = Jobcomment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jobcomment_params
      params.require(:jobcomment).permit(:user_id, :content,:jobpost_id)
    end
end

app/helpers/jobcomments_helper.rb
module JobcommentsHelper
end

app/views/jobcomments/_form.html.erb
<%= form_for(@jobcomment) do |f| %>
  <% if @jobcomment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jobcomment.errors.count, "error") %> prohibited this jobcomment from being saved:</h2>

      <ul>
      <% @jobcomment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.number_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobcomments/edit.html.erb
<h1>Editing Jobcomment</h1>

<%= render 'form' %>

<%= link_to 'Show', @jobcomment %> |
<%= link_to 'Back', jobcomments_path %>

app/views/jobcomments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Jobcomments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobcomments.each do |jobcomment| %>
      <tr>
        <td><%= jobcomment.user_id %></td>
        <td><%= jobcomment.content %></td>
        <td><%= link_to 'Show', jobcomment %></td>
        <td><%= link_to 'Edit', edit_jobcomment_path(jobcomment) %></td>
        <td><%= link_to 'Destroy', jobcomment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jobcomment', new_jobcomment_path %>

app/views/jobcomments/new.html.erb
<h1>New Jobcomment</h1>

<%= render 'form' %>

<%= link_to 'Back', jobcomments_path %>

app/views/jobcomments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @jobcomment.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @jobcomment.content %>
</p>

<%= link_to 'Edit', edit_jobcomment_path(@jobcomment) %> |
<%= link_to 'Back', jobcomments_path %>